apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple
        image: mhausenblas/simpleservice:0.5.0
        ports:
        - containerPort: 9876
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "0.9"
